var points;

function points_behavior_(this_sprite) {
  showTitleScreen(['Points:',points].join(''), '');
}

function math_random_int(a, b) {
  if (a > b) {
    // Swap a and b to ensure a is smaller.
    var c = a;
    a = b;
    b = c;
  }
  return Math.floor(Math.random() * (b - a + 1) + a);
}

function target(this_sprite) {
  moveInDirection(({costume: "animation_2"}), 1, "West");
  if (getProp(({costume: "animation_2"}), "x") == 100) {
    jumpTo(({costume: "animation_2"}), locationAt(200, math_random_int(50, 405)));
  }
}

function moving_with_arrow_keys(this_sprite) {
  if (isKeyPressed("up")) {
    moveInDirection(this_sprite, 5, "North");
  }
  if (isKeyPressed("down")) {
    moveInDirection(this_sprite, 5, "South");
  }
  if (isKeyPressed("left")) {
    moveInDirection(this_sprite, 5, "West");
  }
  if (isKeyPressed("right")) {
    moveInDirection(this_sprite, 5, "East");
  }
}

function moving_west(this_sprite) {
  moveInDirection(this_sprite, 5, "West");
}

function spinning_right(this_sprite) {
  turn(this_sprite, 6, "right");
}

function growing(this_sprite) {
  changePropBy(this_sprite, "scale", 1);
}

function swimming_left_and_right(this_sprite) {
  if (getProp(this_sprite, "direction") == 0) {
    mirrorSprite(this_sprite, "right");
  } else if (getProp(this_sprite, "direction") == 180) {
    mirrorSprite(this_sprite, "left");
  }
  moveForward(this_sprite, 5);
  if (isTouchingEdges(this_sprite)) {
    edgesDisplace(this_sprite);
    changePropBy(this_sprite, "direction", 180);
  }
}

function moving_east(this_sprite) {
  moveInDirection(this_sprite, 5, "East");
}

function moving_north(this_sprite) {
  moveInDirection(this_sprite, 5, "North");
}

function patrolling(this_sprite) {
  moveForward(this_sprite, 5);
  if (isTouchingEdges(this_sprite)) {
    edgesDisplace(this_sprite);
    changePropBy(this_sprite, "direction", 180);
  }
}

function moving_south(this_sprite) {
  moveInDirection(this_sprite, 5, "South");
}

function jittering(this_sprite) {
  changePropBy(this_sprite, "scale", math_random_int(-1, 1));
}

function wandering(this_sprite) {
  if (math_random_int(0, 5) == 0) {
    changePropBy(this_sprite, "direction", math_random_int(-25, 25));
  }
  moveForward(this_sprite, 1);
  if (isTouchingEdges(this_sprite)) {
    edgesDisplace(this_sprite);
    changePropBy(this_sprite, "direction", math_random_int(135, 225));
  }
}

function shrinking(this_sprite) {
  changePropBy(this_sprite, "scale", -1);
}

function spinning_left(this_sprite) {
  turn(this_sprite, 6, "left");
}

function driving_with_arrow_keys(this_sprite) {
  if (isKeyPressed("up")) {
    moveForward(this_sprite, 5);
  }
  if (isKeyPressed("down")) {
    moveBackward(this_sprite, 5);
  }
  if (isKeyPressed("left")) {
    changePropBy(this_sprite, "direction", -5);
    changePropBy(this_sprite, "rotation", -5);
  }
  if (isKeyPressed("right")) {
    changePropBy(this_sprite, "direction", 5);
    changePropBy(this_sprite, "rotation", 5);
  }
  if (isTouchingEdges(this_sprite)) {
    edgesDisplace(this_sprite);
  }
}

printText('Dont click l');
playSound('sound://category_background/progression.mp3');
setBackgroundImage("https://studio.code.org/blockly/media/skins/studio/background_space.png");
makeNewSpriteAnon("flatDark41_1", ({"x":200,"y":200}));

spriteClicked("when", ({costume: "flatDark41_1"}), function (extraArgs) {
  destroy(({costume: "flatDark41_1"}));
  setBackgroundImage("https://studio.code.org/blockly/media/skins/studio/background_space.png");
  points = 0;
  makeNewSpriteAnon("animation_1", ({"x":200,"y":200}));
  makeNewSpriteAnon("animation_2", ({"x":248,"y":182}));
  setProp(({costume: "animation_1"}), "scale", 200);
  addBehaviorSimple(({costume: "animation_2"}), new Behavior(target, []));
});

keyPressed("when", "l", function () {
  printText('I told you dont click are you that dumb to click it');
  for (var count = 0; count < 100; count++) {
    playSound('sound://category_background/progression.mp3');
  }
});

checkTouching("when", ({costume: "animation_1"}), ({costume: "animation_2"}), function (extraArgs) {
  points = (typeof points == 'number' ? points : 0) + 1;
});

atTime(1000, "seconds", function (extraArgs) {
  makeNewSpriteAnon("flatDark41_1", ({"x":200,"y":200}));
  printText('your score');
  showTitleScreen(['points:',points].join(''), '');
});

keyPressed("when", "a", function () {
  hideTitleScreen();
});

keyPressed("while", "right", function () {
  moveInDirection(({costume: "animation_1"}), 10, "East");
  edgesDisplace(({costume: "animation_1"}));
});

keyPressed("while", "left", function () {
  moveInDirection(({costume: "animation_1"}), 10, "West");
  edgesDisplace(({costume: "animation_1"}));
});

keyPressed("when", "space", function () {
  addBehaviorSimple(({costume: "animation_1"}), new Behavior(points_behavior_, []));
});

keyPressed("while", "down", function () {
  moveInDirection(({costume: "animation_1"}), 10, "South");
  edgesDisplace(({costume: "animation_1"}));
});

keyPressed("while", "up", function () {
  edgesDisplace(({costume: "animation_1"}));
  moveInDirection(({costume: "animation_1"}), 10, "North");
});
OK
